### ISSUE TITLE
[Emoji Hatter] UI redesign

### ISSUE THREAD

**Issue by rocksdanister** [dabjulmaros/dabjulmaros.github.io#1]
Remove the sliders, instead make the emoji draggable, resizable etc. 
Similar to image editing software.
Ditch the Generate button.

**Comment by dabjulmaros** [comment]
hello, 
thank you for you idea. Here at dabjulmaros inc trust corporation we are always open for new ideas, that may help and improve our software for our valued users. In regard to your suggestion we really apreciate it. Our code monkeys have looked at it, and plan to implement it:
never.
thank you again,
Dabjulmaros ceo,cto,intern,

**Comment by dabjulmaros** [comment]
Yeah the generate button is hanging from a thread. It may be gone for the next update is planned.
I will keep the sliders for now, if i add more possible layers I may invest into that, but for now sliders are more intuitive in my opinion.
