### ISSUE TITLE
Make it an electron app

### ISSUE THREAD

**Issue by rocksdanister** [dabjulmaros/dabjulmaros.github.io#2]
title.

**Comment by dabjulmaros** [comment]
hello,
thank you for you idea. Here at dabjulmaros inc trust corporation we are always open for new ideas, that may help and improve our software for our valued users. In regard to your suggestion we really apreciate it. Our code monkeys have looked at it, and plan to implement it:
never.
thank you again,
Dabjulmaros ceo,cto,intern,

**Comment by dabjulmaros** [comment]
maybe. It would be a nice intro to electron at least.... There are currently no plans to make it an electron app given that I dont see any benefit for it.
